title: Hello, world! I'm Piyush Tripathi
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, San Francisco, USA
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Piyush Tripathi # add your name
author-img: "profile pic.jpg" # add your photo
about-author: I am a Software Enginner working on cloud computing, AWS and Highly scaled consumer apps. # add description
social-twitter: false # add your Twitter handle
social-facebook: false # add your Facebook handle
social-github: thepiyush13 # add your Github handle
social-linkedin: piyush13 # add your Linkedin handle
social-email: false # add your Email address

# Disqus
discus-identifier: piyushtripathi # add your discus identifier

# Tracker
analytics: UA-152728342-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
